---
title: Phil Coffman
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: pc@philcoffman.com
description: |-
  **Digital Designer & Human**
  Based in Austin, TX
baseurl: 
url: 
twitter_username: philcoffman
github_username: philcoffman
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
