---
title: Phil Coffman
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: pc@philcoffman.com
description: Phil Coffman is a digital designer and lives in Austin, TX with his family.
  He is currently the Design Lead at PCPartPicker.
baseurl: ''
url: https://localhost:4000/
twitter_username: philcoffman
github_username: philcoffman
markdown: kramdown
paginate: 5
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
